param AppServicePlanName = 'SoliriusASP'
param sku = 'Standard_LRS'
param webJobStorageAccountName = 'Solirius_StorageAccount'
param sqlServerName = 'SoliriusSQLServer'
param sqlAdminUsername = 'SoliriusAdmin'
param ASPsku = 'P1v3'
param sqlDbSkuName = 'S1'
param sqlDbSkuTier = 'Standard'
